name: Library CI

on:
  workflow_dispatch:  # Trigger manually

  push:
    paths:
      - "hotel_lib/**"
      - ".github/workflows/**"

jobs:
  lib-tests:        
    uses: ./.github/workflows/build-and-test.yml
    with:
      build_target: hotel_lib_tests
